sudo: required
services:
  - docker

before_install:
  - docker build -t michalmarencak/complex-docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true michalmarencak/complex-docker-react npm test -- --coverage

after_success:
  - docker build -t michalmarencak/multi-client ./client
  - docker build -t michalmarencak/multi-nginx ./nginx
  - docker build -t michalmarencak/multi-server ./server
  - docker build -t michalmarencak/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push michalmarencak/multi-client
  - docker push michalmarencak/multi-nginx
  - docker push michalmarencak/multi-server
  - docker push michalmarencak/multi-worker
